---
name: Testing

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  package_dpkg:
    name: Package for Debian/Ubuntu
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        arch:
          - amd64

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Install packages needed for build
        run: |
          sudo apt-get update
          sudo apt-get install debhelper build-essential \
            crossbuild-essential-${{ matrix.arch }}

      - name: Configure
        # The HOST_TRIPLET line is not easily foldable
        # yamllint disable rule:line-length
        run: |
          # This will warn about CC, but we cannot set CC until we run it :-S
          HOST_TRIPLET=$(dpkg-architecture -a${{ matrix.arch }} -q DEB_HOST_GNU_TYPE)
          export CC=$HOST_TRIPLET-gcc
          export AR=$HOST_TRIPLET-ar
          ./autogen.sh
          ./configure --host $HOST_TRIPLET
          cd packages/debian/
          ./configure EXTN=${{ matrix.arch }}
        # yamllint enable rule:line-length

      - name: Build
        run: |
          cd packages/debian/
          make

      - name: Upload dpkg
        uses: actions/upload-artifact@v3
        with:
          name: packages-dpkg
          path: packages/debian/*.deb
